POST http://localhost:3000/getAllFlashcards HTTP/1.1
content-type: application/json

{
        "spreadsheet_id": "1w8JKb4kko-PIX0y8kBsMr7Kor9KGNFsYKkR6-iNQ3xc",
        "sheet": 0
}

###
POST http://localhost:3000/markCell HTTP/1.1
content-type: application/json

{
        "spreadsheet_id": "1w8JKb4kko-PIX0y8kBsMr7Kor9KGNFsYKkR6-iNQ3xc",
        "sheet": 0,
        "frontside_marking": "YES",
        "position" : 5
}
