name: Deploy to Google Cloud VM

on:
  pull_request:
    types: [closed]
    branches:
      - main
    tags:
      - 'production-*'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      env:
        VM_USER: ${{ secrets.VM_USER }}
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        ssh $VM_USER@$VM_IP 'bash -s' <<'EOF'
          cd /path/to/your/project
          git pull origin main
          npm install
          pm2 reload all
        EOF
